unique_ids:
  forms:
    Tabulator: QVEF2I7ACU32S3FQZZAVWRVYJ2F76DNF
    Tabulator.__StartupForm: DBYX6M2F2RVHN3FP2Z53JBLKKZYEGX2R
  modules:
    Tabulator._CleanCols: SSWGHIACH3VUEVYQ57FYI2DGRAXWP23O
    Tabulator._Helpers: FLYABIDNXG2OADML2KNLPAAWJAM7KWK4
  server_modules: {}
  assets: {}
