unique_ids:
  forms:
    Tabulator: VGSAAILKZP677NZNFCCWW5CXV4MPDRK5
  modules:
    Tabulator._js_tabulator: XU4MLISIUSE7WQ5QOMUO3LPRS2Q7KB6W
    Tabulator._helpers: BH3U5HXSADHIZFJLBQN3DCM4SRISJQ6S
    Tabulator._data_loader: KILFR7KJ4L3LSZGKKZLUAJTJXYZYTRIF
    Tabulator._custom_modules: Q6HTPEC4U6O6JLMU5FVAQFS2D3Y72HCV
    Tabulator._module_helpers: 2BZYQZPLKFG2GCXIQLAPKYCDPIQHGEGA
    Tabulator._datetime_overrides: IXNIGLCRIRZED7TITELUCMUOPFTIV3SX
    Tabulator._defaults: CLZ7EWWDPHSE3P3WIUQGUDKR7CMXJYAE
  server_modules: {}
  assets: {}
